### ISSUE TITLE
The bot unfollowes a lot less people than hes supposed to

### ISSUE THREAD

**Issue by jesusismybrother** [ugurozturk/instabot.pyV2#25]
Hi,
even tho i have over 1400 unfollows per dey and only 800 follows a day my following increases by more than 300 per day.
Here are my parameters:
follow_per_day=800,
    follow_time=1* 60,
    unfollow_per_day=1400,
    unfollow_break_min=2,
    unfollow_break_max=5,

I would be happy if you could help me =)

**Comment by zephyrspikie27391** [comment]
I  haven't tried the follow on this script but does yours follow new people and then unfollows the new people only or does it unfollow your friends before too?

**Comment by ugurozturk** [comment]
@jesusismybrother it does only unfollow whose bot did follow. Btw it is not recommended by using this much. You might get ban because of that. Yet about the following increases 300 per day, i made some changes on the code side. Also check error.log if you find "except on auto_unfollow!" input in the file send the file here. 
Also it does unfollow user if
```
self.is_selebgram is not False
or self.is_fake_account is not False
or self.is_active_user is not True
or self.is_follower is not True
```
So if the user is following you, not selegram, not fake, and active then the bot doesn't unfollow it.

**Comment by ugurozturk** [comment]
Anyhow if you want to unfollow anybody here the feature request https://github.com/ugurozturk/instabot.pyV2/issues/26
